### ISSUE TITLE
Compilation problem (missing stub for _open)

### ISSUE THREAD

**Issue by ajneu** [arobenko/embxx_on_rpi#1]
Hello,

with Debian Testing and the following packages for cross-compiler:

``` bash
sudo apt-get install gcc-arm-none-eabi gdb-arm-none-eabi libstdc++-arm-none-eabi-newlib libnewlib-arm-none-eabi binutils-arm-none-eabi 
```

... I get some errors when compiling embxx_on_rpi:

```
cd /tmp/a/embxx_on_rpi/build/src/test_cpp/test_cpp_vector && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_cpp_vector.dir/link.txt --verbose=1
arm-none-eabi-g++   --std=c++0x -Wall -Wextra -Werror -Woverloaded-virtual -Wno-unused-local-typedefs -march=armv6z -fno-exceptions -fno-unwind-tables -fno-rtti  -Wl,-Map,kernel.map -T /tmp/a/embxx_on_rpi/src/raspberrypi.ld CMakeFiles/test_cpp_vector.dir/main.cpp.o CMakeFiles/test_cpp_vector.dir/stub.cpp.o CMakeFiles/test_cpp_vector.dir/heap.cpp.o  -o test_cpp_vector  ../../asm/libstartup.a 
/usr/lib/gcc/arm-none-eabi/4.9/../../../arm-none-eabi/lib/libc.a(lib_a-openr.o): In function `_open_r':
/home/tin/projects/debian/arm-toolchain/collab-maint/newlib/build/arm-none-eabi/newlib/libc/reent/../../../../../newlib/libc/reent/openr.c:59: undefined reference to `_open'
collect2: error: ld returned 1 exit status
```
#### A solution is to provide a stub for `_open`

In the following files:
- [src/test_cpp/test_cpp_exceptions/stub.cpp](https://github.com/arobenko/embxx_on_rpi/blob/master/src/test_cpp/test_cpp_exceptions/stub.cpp)
- [src/test_cpp/test_cpp_vector/stub.cpp](https://github.com/arobenko/embxx_on_rpi/blob/master/src/test_cpp/test_cpp_vector/stub.cpp)

one can add something like:

``` cpp
// This stub function is required by stdlib
extern "C" int _open(const char *name, int flags, int mode)
{
    static_cast<void>(name);
    static_cast<void>(flags);
    static_cast<void>(mode);
    return -1;   // does the stub-return need to be a specific value??
}
```

[Ref-Link](https://sourceware.org/newlib/libc.html#index-open)

Thanks for sharing your book (and code) on BareMetal with C++. Just started and it looks fantastic!

**Comment by arobenko** [comment]
Hi,
Thanks for letting me know.
The "bare metal C++" was kind of hobby project for me a year ago. At this moment I work on something else though.
Once I decide to get back to it a bit later I will introduce the fix for the missing "_open" function you reported.
