### ISSUE TITLE
Device - Function compiler errors (gcc v5.x)

### ISSUE THREAD

**Issue by 0xc0170** [arobenko/embxx_on_rpi#4]
I mentioned this in the previous pull request. What was the last gcc version this worked ? 

My current version: `arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors) 5.2.1 20151202 (release) [ARM/embedded-5-branch revision 231848]`

```
[ 55%] Building CXX object src/device/CMakeFiles/device.dir/Function.cpp.obj
path/embxx_on_rpi/src/device/Function.cpp:45:1: error: non-constant condition for static assertion
 static_assert(&pSel->entries[0] == reinterpret_cast<SingleSelWord*>(0x20200000),
 ^
path/embxx_on_rpi/src/device/Function.cpp:45:1: error: expression '((volatile device::{anonymous}::SelWords*)device::{anonymous}::pSel)->device::{anonymous}::SelWords::entries[0]' has side-effects
path/embxx_on_rpi/src/device/Function.cpp:47:1: error: non-constant condition for static assertion
 static_assert(&pSel->entries[1] == reinterpret_cast<SingleSelWord*>(0x20200004),
 ^
path/embxx_on_rpi/src/device/Function.cpp:47:1: error: expression '((volatile device::{anonymous}::SelWords*)device::{anonymous}::pSel)->device::{anonymous}::SelWords::entries[1]' has side-effects
path/embxx_on_rpi/src/device/Function.cpp:49:1: error: non-constant condition for static assertion
 static_assert(&pSel->entries[2] == reinterpret_cast<SingleSelWord*>(0x20200008),
 ^
path/embxx_on_rpi/src/device/Function.cpp:49:1: error: expression '((volatile device::{anonymous}::SelWords*)device::{anonymous}::pSel)->device::{anonymous}::SelWords::entries[2]' has side-effects
path/embxx_on_rpi/src/device/Function.cpp:51:1: error: non-constant condition for static assertion
 static_assert(&pSel->entries[3] == reinterpret_cast<SingleSelWord*>(0x2020000C),
 ^
path/embxx_on_rpi/src/device/Function.cpp:51:1: error: expression '((volatile device::{anonymous}::SelWords*)device::{anonymous}::pSel)->device::{anonymous}::SelWords::entries[3]' has side-effects
path/embxx_on_rpi/src/device/Function.cpp:53:1: error: non-constant condition for static assertion
 static_assert(&pSel->entries[4] == reinterpret_cast<SingleSelWord*>(0x20200010),
 ^
path/embxx_on_rpi/src/device/Function.cpp:53:1: error: expression '((volatile device::{anonymous}::SelWords*)device::{anonymous}::pSel)->device::{anonymous}::SelWords::entries[4]' has side-effects
path/embxx_on_rpi/src/device/Function.cpp:55:1: error: non-constant condition for static assertion
 static_assert(&pSel->entries[5] == reinterpret_cast<SingleSelWord*>(0x20200014),
 ^
path/embxx_on_rpi/src/device/Function.cpp:55:1: error: expression '((volatile device::{anonymous}::SelWords*)device::{anonymous}::pSel)->device::{anonymous}::SelWords::entries[5]' has side-effects
make[2]: *** [src/device/CMakeFiles/device.dir/Function.cpp.obj] Error 1
make[1]: *** [src/device/CMakeFiles/device.dir/all] Error 2
make: *** [all] Error 2
```

I am slowly tracking issues. Seems like there were some C++11 changes introduced in GCC 5, therefore this can be a problem. I am currently investigating other issue where I found out about GCC 5 c++11 changeset :)

**Comment by 0xc0170** [comment]
Based on this, I created an issue in embxx to see if I shall revert to gcc 4.x for this project, it might resolve this issue. I'll give it a shot.

**Comment by 0xc0170** [comment]
Tested with gcc arm v4.9, this problem disappears. I'll switch to v4.9 for now, and see what we can do about https://github.com/arobenko/embxx/issues/5

**Comment by arobenko** [comment]
I just verified that the addresses of the entries are just as I expect them to be. The last time I tried to compile this code was more than a year ago using g++-4.8 on Linux. I suppose the newer versions of gcc don't like these statements.
What I was trying to do is to verify that compiler doesn't add anything else hidden into the SelWords structure. Try to remove all these static_assert statements and replace them with:
static_assert(sizeof(SelWords) == sizeof(SingleSelWord[NumOfSelWords]), "Unexpected compiler behaviour")

**Comment by ajneu** [comment]
I can confirm the findings of Martin.

Just for fun... another way of handling it that's close to the original would be:

``` cpp
static_assert(offsetof(SelWords, entries) == 0,
     "Select entry address is not as expected");
static_assert(offsetof(SelWords, entries[1]) == 4,
     "Select entry address is not as expected");
static_assert(offsetof(SelWords, entries[2]) == 8,
     "Select entry address is not as expected");
static_assert(offsetof(SelWords, entries[3]) == 12,
     "Select entry address is not as expected");
static_assert(offsetof(SelWords, entries[4]) == 16,
     "Select entry address is not as expected");
static_assert(offsetof(SelWords, entries[5]) == 20,
     "Select entry address is not as expected");
```

Oh and it seems that the `embxx/cmake/CompilerOptionsFuncs.cmake` is having weird behaviour regarding my commit of `CMAKE_CXX_STANDARD`: [link](https://github.com/arobenko/embxx/blob/ed6ee7697ddc86a4aa368e7311c4a28cfc45d4c3/cmake/CompilerOptionsFuncs.cmake#L77). But only when pulled into this repo (_embxx_on_rpi_) via external project / submodule. In the _embxx_ repo itself, it's all fine. Strange.
I need some time to figure out why it's not working as expected, in this repo with submodule.

**Comment by ajneu** [comment]
> Oh and it seems that the `embxx/cmake/CompilerOptionsFuncs.cmake` is having weird behaviour regarding my commit of `CMAKE_CXX_STANDARD`: [link](https://github.com/arobenko/embxx/blob/ed6ee7697ddc86a4aa368e7311c4a28cfc45d4c3/cmake/CompilerOptionsFuncs.cmake#L77). But only when pulled into this repo (_embxx_on_rpi_) via external project / submodule. In the _embxx_ repo itself, it's all fine. Strange.
> I need some time to figure out why it's not working as expected, in this repo with submodule.

I think this might be a CMake bug, where the flag `CMAKE_CXX_STANDARD` has no effect on a crosscompiler. I've filed a bug-report [here](http://public.kitware.com/Bug/view.php?id=16004). (I wonder what the cmake-experts will say).

**Comment by arobenko** [comment]
Should be fixed in "develop" branch
